server:
  port: 8011
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/inflearn_proto
    username: sbsst
    password: sbs123414
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
